def custom_song(name1, name2, location, object1, object2, adj, job, goal):
    print("\n")
    print(f"{name1} and {name2} were a few fine folk")
    print(f"Made love in the morning with a few high hopes")
    print(f"They'd leave a note and kick up dirt")
    print (f"In a {location} only good for part-time work")
    print(f"They bought an {object2} and loaded {object1}")
    print(f"To head to {location} where the weather's {adj}")
    print(f"They might steer south where the river's red")
    print(f"Only thing they need now is each other or dead")
    print("\n")
    print(f"{name1} went to work nearly every day")
    print(f"And in one month's time they'll be on their way")
    print(f"{name2} prepared the {object2} you see")
    print(f"For a getaway bound for {job}")
    print("\n")
    print(f"Won't you load up this bag because my sweet {name2} is tired?")
    print(f"I promised {name2} a life and I swear to God I'll fire")
    print(f"'Cause {name2}'s stomach it keeps turning")
    print(f"My hands are callused rock")
    print(f"I'd rather die a desperate {job} than a {job} that got caught")
    print("\n")
    print(f"{name1} made it out alive and looked {name2} in the eyes")
    print(f"Told {name2} no more scraping by")
    print(f"We're gonna be {goal}")
    print(f"They stand so brave in a house out east")
    print(f"And tonight {name2}'s cooking a feast for the two of them")

# Collecting user inputs
name1 = input("Enter the first person's name: ")
name2 = input("Enter the second person's name: ")
location = input("Enter a place name: ")
object1 = input("Enter an object: ")
object2 = input("Enter a vehicle: ")
adj = input("Enter an adjective to describe the weather: ")
job = input("Enter a type of work: ")
goal = input("Enter a goal or aspiration: ")

# Calling the function
custom_song(name1, name2, location, object1, object2, adj, job, goal)
